version: "3.2"
services:
  backend:
    build: ./
    volumes:
      - ./:/app/backend
    ports:
      - "8091:8091"
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8091
  frontend:

    build: ./priority-analyser-frontend
    volumes:
      - ./priority-analyser-frontend:/app/frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    command: npm start